[package]
name = "golem-base-sdk-example"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = "0.15"
bytes = "1.0"
dirs = "6.0"
env_logger = "0.11"
golem-base-sdk = { path = ".." }
log = "0.4"
tokio = { version = "1.44", features = ["full"] }