[package]
name = "golem-base-sdk"
version = "0.1.0"
edition = "2021"
description = "A Rust SDK for interacting with GolemBase storage contracts."
license = "MIT"

[workspace]
members = [
    "example",
    "cli"
]


[dependencies]
alloy = { version = "0.15", features = ["full", "json-rpc"] }
alloy-signer-local = { version = "0.15", features = ["keystore"] }
alloy-rlp = "0.3"
alloy-json-rpc = "0.15"
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.22"
bytes = "1.0"
bigdecimal = "0.4"
bon = "3.6"
dirs = "5.0"
displaydoc = "0.2"
hex = "0.4"
log = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "2.4"
thiserror = "2.0"

[workspace.dependencies]
golem-base-sdk = { path = "." }

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.10"
