[package]
name = "golem-base-sdk"
version = "0.1.0"
edition = "2021"
description = "A Rust SDK for interacting with GolemBase storage contracts."
license = "MIT"
repository = "https://github.com/Golem-Base/rust-sdk"
documentation = "https://docs.rs/golem-base-sdk"

[dependencies]
alloy = { version = "0.15", features = ["json-rpc"] }
alloy-rlp = { version = "0.3", features = ["derive"] }
base64 = "0.22"
bon = "3.6"
displaydoc = "0.2"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
