# Composite GitHub Action for setting up the test environment.
#
# - Starts a `gb-op-geth` container for Ethereum-compatible RPC.
# - Checks out the `gb-op-geth` repo and sets up Go.
# - Creates and funds a test account.
#
# To use, reference this action in your workflow with `uses:`.

runs:
  using: "composite"
  steps:
    - name: Run a gb-op-geth container
      run: >
        docker run -d -p 8545:8545 -e GITHUB_ACTIONS=true -e CI=true
        quay.io/golemnetwork/gb-op-geth:latest --dev --http --http.api
        'eth,web3,net,debug,golembase' --verbosity 3 --http.addr '0.0.0.0' --http.port 8545
        --http.corsdomain '*' --http.vhosts '*' --ws --ws.addr '0.0.0.0' --ws.port 8545
      shell: bash

    - name: Check out the gb-op-geth repo
      uses: actions/checkout@v4
      with:
        repository: Golem-Base/golembase-op-geth
        path: gb-op-geth

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.2"

    - name: Create and fund an account
      run: |
        printf "password" | go run ./cmd/golembase account create
        printf "password" | go run ./cmd/golembase account fund
      working-directory: ./gb-op-geth
      shell: bash
