[package]
name = "golem-base-test-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.24", features = ["full", "json-rpc"] }
anyhow = "1.0"
bigdecimal = "0.4"
env_logger = "0.11.8"
log = "0.4"

dirs = "6.0.0"
golem-base-sdk = { workspace = true }
url = "2.5.4"
