[package]
name = "golem-base-sdk-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0"
env_logger = "0.11"
futures = "0.3"
golem-base-sdk = { workspace = true }
log = "0.4"
tokio = { version = "1", features = ["full"] }
