name: Run examples and tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the SDK repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Go and Arkiv
        uses: ./.github/workflows/setup

      # TODO: This could probably just be a derivation
      - name: Run Rust demo example
        run: printf "password" | nix develop --command cargo run
        working-directory: ./demo

  run-tests-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the SDK repo
        uses: actions/checkout@v4

      - name: Setup Go, Rust and Arkiv
        uses: ./.github/workflows/setup

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run tests
        run: nix flake check --keep-going -L

      - name: Build docs
        run: nix build .#checks.x86_64-linux.cargo-doc

      - name: Deploy docs to branch folder
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/share/doc
          publish_branch: gh-pages
          destination_dir: ${{ github.head_ref }}

      - name: Comment PR with docs URL
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview the generated documentation for this PR at:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.head_ref }}/arkiv_sdk/
