name: Run examples and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  rust_stable: 1.84.0

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the SDK repo
        uses: actions/checkout@v4

      - name: Setup Go, Rust and Golem Base
        uses: ./.github/workflows/setup

      - name: Run Rust demo example
        run: cargo run
        working-directory: ./example

      - name: Run Rust yagna interaction example
        run: cargo run --example yagna_interaction

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the SDK repo
        uses: actions/checkout@v4

      - name: Setup Go, Rust and Golem Base
        uses: ./.github/workflows/setup

      - name: Run tests
        run: cargo test
